### ISSUE TITLE
stringImportPaths very slow

### ISSUE THREAD

**Issue by jacob-carlborg** [dlang/dub#1199]
I'm working on making DMD available as a Dub package [1]. I need to set the string import path, but when using the `stringImportPaths` configuration it's very slow to build. Running `dub build :parser --vverbose` shows that all time is spent on the step: `Using configuration 'library' for dmd:lexer`. It also ends with a failure: `Invalid variable: DFLAGS`. The full stacktrace is:

```
Using configuration 'library' for dmd:lexer
Invalid variable: DFLAGS
Full exception: object.Exception@source/dub/project.d(1233): Invalid variable: DFLAGS
----------------
4   dub                                 0x0000000103ece763 immutable(char)[] dub.project.getVariable(immutable(char)[], const(dub.project.Project), const(dub.package_.Package)) + 591
5   dub                                 0x0000000103ece407 immutable(char)[] dub.project.processVars(immutable(char)[], const(dub.project.Project), const(dub.package_.Package), bool) + 619
6   dub                                 0x0000000103ece180 void dub.project.processVars(ref std.array.Appender!(immutable(char)[][]).Appender, const(dub.project.Project), const(dub.package_.Package), immutable(char)[][], bool) + 124
7   dub                                 0x0000000103ece0f4 immutable(char)[][] dub.project.processVars(const(dub.project.Project), const(dub.package_.Package), immutable(char)[][], bool) + 64
8   dub                                 0x0000000103ecddf1 void dub.project.processVars(ref dub.compilers.buildsettings.BuildSettings, const(dub.project.Project), const(dub.package_.Package), dub.compilers.buildsettings.BuildSettings, bool) + 317
9   dub                                 0x0000000103f1cdc2 D3dub10generators9generator16ProjectGenerator8generateMFS3dub10generators9generator17GeneratorSettingsZ14__foreachbody2MFKC3dub8package_7PackageZi + 294
10  dub                                 0x0000000103ec6f82 D3dub7project7Project25getTopologicalPackageListMxFbxC3dub8package_7PackageHAyaAyaZ8iteratorMFDFKxC3dub8package_7PackageZiZ11perform_recMFxC3dub8package_7PackageZv + 934
11  dub                                 0x0000000103ec6f3d D3dub7project7Project25getTopologicalPackageListMxFbxC3dub8package_7PackageHAyaAyaZ8iteratorMFDFKxC3dub8package_7PackageZiZ11perform_recMFxC3dub8package_7PackageZv + 865
12  dub                                 0x0000000103ec6bce D3dub7project7Project25getTopologicalPackageListMxFbxC3dub8package_7PackageHAyaAyaZ8iteratorMFDFKxC3dub8package_7PackageZiZi + 90
13  dub                                 0x0000000103f1c9ca void dub.generators.generator.ProjectGenerator.generate(dub.generators.generator.GeneratorSettings) + 318
14  dub                                 0x0000000103e9013f void dub.dub.Dub.generateProject(immutable(char)[], dub.generators.generator.GeneratorSettings) + 155
15  dub                                 0x0000000103e73c08 int dub.commandline.GenerateCommand.execute(dub.dub.Dub, immutable(char)[][], immutable(char)[][]) + 1484
16  dub                                 0x0000000103e73f91 int dub.commandline.BuildCommand.execute(dub.dub.Dub, immutable(char)[][], immutable(char)[][]) + 125
17  dub                                 0x0000000103e703b9 int dub.commandline.runDubCommandLine(immutable(char)[][]) + 3301
18  dub                                 0x0000000103e6b667 _Dmain + 31
19  dub                                 0x000000010402f7a7 D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv + 39
20  dub                                 0x000000010402f6d3 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 35
21  dub                                 0x000000010402f74c void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() + 44
22  dub                                 0x000000010402f6d3 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 35
23  dub                                 0x000000010402f639 _d_run_main + 497
24  dub                                 0x0000000103e6b6ff main + 15
25  libdyld.dylib                       0x00007fffa2c86234 start + 0
26  ???                                 0x0000000000000003 0x0 + 3
```

If I'm using the `dflags` configuration to manually specify the `-J` flag everything works fine.

[1] https://github.com/dlang/dmd/pull/6771

**Comment by s-ludwig** [comment]
The slow preparation time should be fixed by #1125, which will be in 1.4.0/2.075.0. As for the "DFLAGS" error, I'm not sure. Can you paste the failing dub.sdl? Or is the only change over the current version `dflags "-J$PACKAGE_DIR"` -> `stringImportPaths "."`?

**Comment by jacob-carlborg** [comment]
> Or is the only change over the current version dflags "-J$PACKAGE_DIR" -> stringImportPaths "."?

Yes. I also tried `stringImportPaths "$PACKAGE_DIR"` but that won't expand `$PACKAGE_DIR`.

**Comment by jacob-carlborg** [comment]
I'm still having problems with this using DUB 1.4.0. Now it spends all time at this step:

```
Generate target dmd:root (staticLibrary /Users/jacob/development/d/dlang/dmd dmd_root)
```

Using `stringImportPaths "."` takes 1 minute and 41 seconds. Using `dflags "-J$PACKAGE_DIR"` takes 0.3 seconds.

**Comment by jacob-carlborg** [comment]
Full DUB file:

```
name "dmd"
description "The DMD compiler"
authors "Walter Bright"
copyright "Copyright © 1999-2017, Digital Mars"
license "BSL-1.0"

targetType "none"
dependency ":parser" version="*"

subPackage {
  name "root"
  targetType "library"
  sourcePaths "src/ddmd/root"
}

subPackage {
  name "lexer"
  targetType "library"
  sourcePaths

  sourceFiles \
    "src/ddmd/console.d" \
    "src/ddmd/entity.d" \
    "src/ddmd/errors.d" \
    "src/ddmd/globals.d" \
    "src/ddmd/id.d" \
    "src/ddmd/identifier.d" \
    "src/ddmd/lexer.d" \
    "src/ddmd/tokens.d" \
    "src/ddmd/utf.d"

  // stringImportPaths cannot be used because it will make Dub extremely slow
  // https://github.com/dlang/dub/issues/1199
  // dflags "-J$PACKAGE_DIR"
  stringImportPaths "."

  dependency "dmd:root" version="*"
}

subPackage {
  name "parser"
  targetType "library"
  sourcePaths

  sourceFiles \
    "src/ddmd/astbase.d" \
    "src/ddmd/astbasevisitor.d" \
    "src/ddmd/parse.d"

  dependency "dmd:lexer" version="*"
}
```

**Comment by MartinNowak** [comment]
Well the reason is simply that dub checks all files in the string import path as build dependencies, since you're using the root folder, that includes all of dmd's tests and whatnot.
This already produces way too many stat calls, but basic profiling shows that it spends most time here https://github.com/dlang/dub/blob/dafdc47d690c63d074e1b9ed57349fe2eaaabd2b/source/dub/generators/generator.d#L245-L255. Isn't there a decent profiler on OSX? Finding such issues with [perf](https://perf.wiki.kernel.org/index.php/Main_Page) on Linux usually takes a couple of seconds.

**Comment by MartinNowak** [comment]
It's a bit annoying that you're including the whole root folder just for the VERSION file.
Since you'll run into issues for dmd's `SYSCONFDIR.imp` anyhow, I'd recommend to just include some a generated folder and copy the VERSION file there. Maybe it would even make sense to use the `generated/$OS/$BUILD/$ARCH` logic of dmd.

**Comment by jacob-carlborg** [comment]
> Well the reason is simply that dub checks all files in the string import path as build dependencies, since you're using the root folder, that includes all of dmd's tests and whatnot.

It works perfectly fine with using just the `-J` flag. I don't know what DUB is doing that makes it so much slower than DMD.

> Isn't there a decent profiler on OSX?

Yes, there's Instruments.

> Since you'll run into issues for dmd's SYSCONFDIR.imp anyhow

What kind of issues?

> I'd recommend to just include some a generated folder and copy the VERSION file there

Do you suggest that the DUB recipe should copy the `VERSION` file?

BTW, `stringImportPaths` doesn't expand environment variables so it cannot be used anyway.

**Comment by MartinNowak** [comment]
> It works perfectly fine with using just the -J flag. I don't know what DUB is doing that makes it so much slower than DMD.

It tracks dependencies for rebuilds.

> BTW, stringImportPaths doesn't expand environment variables so it cannot be used anyway.

Why would it need any env variables?

**Comment by jacob-carlborg** [comment]
> Why would it need any env variables?

For `$PACKAGE_DIR`

**Comment by MartinNowak** [comment]
It's relative to the package path anyhow, shouldn't need any `$PACKAGE_DIR`.

**Comment by jacob-carlborg** [comment]
Yeah, I understand now that `stringImportPaths` works with relative paths.
